name: Generate Stats Images
on:
  schedule:
     - cron: "10 * * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: TBXark/TBXark
        ref: stats
        fetch-depth: 1

    - name: Download generate-stats binary
      run: |
        if [ "$(uname -m)" = "x86_64" ]; then
          curl -L -o github-status.tar.gz https://github.com/TBXark/github-status/releases/download/0.0.1/github-status_linux_x86.tar.gz
        else
          curl -L -o github-status.tar.gz https://github.com/TBXark/github-status/releases/download/0.0.1/github-status_linux_arm64.tar.gz
        fi
        tar -xzf github-status.tar.gz
        chmod +x github-status

    - name: Generate Stats
      env:
        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        CUSTOM_ACTOR: ${{ secrets.CUSTOM_ACTOR }}
        EXCLUDE_REPOS: ${{ secrets.EXCLUDE_REPOS }}
        EXCLUDE_LANGS: ${{ secrets.EXCLUDE_LANGS }}
        INCLUDE_OWNER: ${{ secrets.INCLUDE_OWNER }}
        IGNORE_PRIVATE_REPOS: ${{ secrets.IGNORE_PRIVATE_REPOS }}
        IGNORE_FORKED_REPOS: ${{ secrets.IGNORE_FORKED_REPOS }}
        IGNORE_ARCHIVED_REPOS: ${{ secrets.IGNORE_ARCHIVED_REPOS }}
        IGNORE_CONTRIBUTED_TO_REPOS: ${{ secrets.IGNORE_CONTRIBUTED_TO_REPOS }}
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      run: ./github-status --output .

    - name: Commit and push if changed
      run: |
        git config --global user.name 'generate-stats'
        git config --global user.email 'generate-stats@tbxark.com'
        git add overview.svg languages.svg
        git diff --staged --quiet || git commit -m "chore: Update stats" && git push
