name: Generate Stats Images
on:
  schedule:
     - cron: "10 * * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: TBXark/TBXark
        ref: stats

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    
    - name: Install generate-stats
      run: go install github.com/TBXark/generate-stats@latest

    - name: Generate Stats
      run: generate-stats -o .

    - name: Commit and push if changed
      run: |
        git config --global user.email "generate-stats@tbxark.com"
        git config --global user.name "generate-stats"
        git add .
        git commit -m "chore: Update stats" --quiet > /dev/null 2>&1 || exit 0
        git push --set-upstream origin stats --quiet > /dev/null 2>&1 || exit 0
